# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

resources:
  repositories:
  - repository: eShopOnWeb
    type: git
    name: eShopOnWeb
  
steps:
- task: CmdLine@2
  inputs:
    script: |
      docker login -u $(registryName) -p $(registryPassword) $(registryUrl)
      docker build . -t $(registryUrl)/eshoponweb:latest
      docker push $(registryUrl)/eshoponweb:latest
